<script setup>
import { computed } from 'vue'
import { useData } from 'vitepress'
const { page } = useData()
const slug = computed(() => page.value.relativePath.replace(/^yerlesimler\//, '').replace(/\.md$/, ''))
const life = {
  'hal-sur':['Vardiya düdükleri beyaz galerilerin gününü böler; tuz tozu saçta, giyside ve ekmekte kalır. Hissedar ailelerinin üst geçitleri serinken Goblin Derinliği sürekli sıcak ve kalabalıktır.','Pazarlar tuz külçesi, cenaze keteni ve simya şişeleriyle dolar. Çoğu işçi oy veremez ama hangi mahzenin havalandırılacağını onlar bilir; bu bilgi günlük pazarlığın gerçek gücüdür.'],
  ankitas:['Kristal salonlarda konuşmalar kayda alınırken sokakta insanlar cümlelerini seçerek kurar. Meclis günlerinde element ocaklarının elçileri renkli işaretlerle mahalleleri doldurur.','Arşiv çırağı, kervancı ve maden işçisi aynı çayevinde oturabilir; fakat bir kaydın kamuya açılması ailelerin ve ocakların itibarını bir gecede değiştirebilir.'],
  velis:['Maskeler Velis’te bayram kostümü değil, gündelik nezakettir. Rıhtımda bir adla borç alan kişi akşam başka bir yüzle senatoya gidebilir.','Sigorta yazıcıları, kılavuzlar ve kimlik tanıkları şehrin görünmez emekçileridir. Ziyaretçi için doğru rehberi bulmak, doğru hanı bulmaktan önemlidir.'],
  nivarra:['Kısa yaz pazarında donmuş balık, sıcak çorba ve buzdan çıkarılmış eski eşyalar yan yana satılır. Kışın mahalleler buz tünelleriyle birbirine bağlanır.','Arşiv bekçileri eriyen duvarları kaydeder; aşçılar ve işçiler su depolarını korur. Şehirde geçmiş, bazen bir buz bloğunun içinden bakar.'],
  solkar:['Teraslarda sabah hasat duası, akşam askerî geçit görülür. Su depolarının başında kuyruk, saray avlularında ise iki tacın dedikodusu eksik olmaz.','Şarapçılar, baharatçılar ve paralı asker simsarları aynı gölgelikte pazarlık eder. Halk, savaş tacı tartışmasının önce kendi ekmeğini ve suyunu etkilediğini bilir.'],
  'bakir-meclis':['Her prenslik geçici yaprak köşk kurduğu için şehir mevsim değiştikçe yeniden düzenlenir. Kalıcı heykel yasağı, sokakları anıt yerine hikâyelerle doldurur.','Elçiler, cenaze aileleri ve yaprak dokumacıları kentin gündelik yüzüdür. Bir oyun boş kaldığında herkesin konuştuğu şey savaş değil, kimin söz hakkı olduğudur.'],
  filizliman:['İskeleler tohum sandıkları, ilaç demetleri ve borç defterleriyle güne başlar. İlkbahar yaklaşınca affedilecek borçların söylentisi kahvehaneleri doldurur.','Bankacıların taş konakları ile rahiplerin açık pazar ayinleri yan yanadır. Halk için şehir, hem yeni başlangıç hem de eski borcun hesabıdır.'],
  vardessa:['Katmanlı surlarda her mahalle başka bir sığınmacı dalgasının taşını taşır. Yukarı katlar geçit ailelerine, aşağı sokaklar paralı askerlere ve zanaatkârlara aittir.','Hanlar sürekli asker, göçmen ve casus değiştirir. Tarafsızlık burada huzur değil, herkesle konuşabilmek için sürdürülen yorucu bir meslektir.'],
  'kirk-kopru':['Köprü başlarında ayrı vergi, saat ve pazar kuralları geçer; bir adadan diğerine geçmek kısa bir yolculuktan çok hukuk değişimidir.','Katipler, tekneciler ve tahıl tüccarları gündeliği yönetir. Kırk birinci köprü tartışması çocuk oyunlarından evlilik sözleşmelerine kadar her sohbete sızmıştır.'],
  'gok-esigi':['Rüzgâr merdivenleri ve manastır avluları günün ritmini belirler. Çan sesleri, hava durumu kadar haber ve yas ilanı da taşır.','Öğrenciler kehanet metinleriyle, rehberler geçit haritalarıyla uğraşır. Rüzgâr yokken çalan çanlar, şehir halkı için akademik bir bilmeceden çok huzursuz bir gündelik sestir.'],
  'demir-talim':['Sokaklar talim saatine göre boşalır, meydanlar depoya dönüşür. Fırınlar birlik vardiyalarına göre ekmek çıkarır.','Hobgoblin aileleri disiplinle yaşar ama aynı okuldan mezunların farklı cephelerde buluşma ihtimali evlerde sessiz bir kaygıdır.'],
  'kizil-meridyen':['Ana cadde boyunca dükkânlar ölçüm çizgisine göre hizalanır; çocuklar bile taşların aralığını sayarak büyür.','Rahipler, ölçümcüler ve mühür ustaları şehrin saygı gören yüzüdür. Caddenin kaydığı söylentisi açıkça konuşulmaz, ama herkes ayakkabısının altındaki farkı bilir.'],
  serath:['Dökümhane dumanı ve akademi boruları günün sesini belirler. Çıraklar silah parçası taşır, subay adayları köprülerde yürüyüş çalışır.','Mühendis loncaları ile asker aileleri aynı pazarda alışveriş eder; Varessa ve Odran tartışması burada ideoloji değil iş emri ve maaş meselesidir.'],
  'saar-kor':['Kaldera teraslarında yaşamak merkezden uzaklaştıkça daha serin ve daha ucuzdur. Soy arşivlerine yakın evler statü göstergesidir.','Ateş işçileri, mezar rehberleri ve savaş öğrencileri şehrin ritmini kurar. Alt ocaklardaki yeni sıcaklık, bazıları için umut, bazıları için tahliye hazırlığıdır.'],
  prizma:['Yedi renkli ışık, günün işlerini bile ayırır: bir mahalle eğitim, biri bakım, biri meclis için uyanır.','Manastır öğrencileri ve kristal zanaatkârları sakin bir düzen taşır. Eski hafızaların söz hakkı, sıradan yurttaş için hangi kararın gerçekten yeni olduğu sorusudur.'],
  mazaros:['Kıvrımlı sokaklar limana rüzgâr ve düşman sokmaz; denizciler yön bulmayı çocukken öğrenir. Tersaneler gece de çalışır.','Kaptan, halatçı ve sigorta yazıcısı aynı sofrada oturur. Ortak donanma fikri her fırtınada cazip, her vergi gününde tartışmalıdır.'],
  'ruzgar-cemberi':['Kurultay dışında rüzgârlı bir boşluktur; toplantı zamanı çadırlar, sürüler ve hikâye ateşleri ufka kadar uzanır.','Kalıcı taş yapı yasağı, misafirin bile zemine nasıl bastığını önemli kılar. Yol hakkı, burada haritadaki çizgiden çok günlük konukluk kuralıdır.'],
  sazkalp:['Saz platformları sabah su seviyesiyle birlikte yer değiştirir. Çocuklar yürümeyi köprü yerine kanallarda öğrenir.','Su mühendisleri pazar esnafı kadar tanınır; bir kapak emri hangi ailenin pirinç yiyeceğini belirler.'],
  'yesil-dis':['Saz surları sürekli onarılır, nehir ağzında nöbet ve balıkçılık iç içedir. Şehir askerîdir ama hayatı çamur, tekne ve aile bahçeleri taşır.','Sınır yangınlarının kokusu geldiğinde herkes su depolarını kontrol eder; savaş söylentisi gündelik hazırlığın parçasıdır.'],
  'uc-yumurta':['Kuluçka adalarında rahip nöbetleri ve şifacı bahçeleri birlikte yürür. Sessizlik, bakım yapanların ortak dili sayılır.','Genç bilginler kalıntıların bilgisini isterken yaşlılar korunmasını savunur; bu tartışma evlerde tedavi yönteminden şehir kimliğine kadar sürer.'],
  'dokuz-can-pazari':['Ağaç yolları ile nehir platformları arasında pazar her gün başka biçim alır. Hikâye, harita ve nadir ürün aynı tezgâhta maldır.','Kenku kayıtçıları ile Tabaxi aileleri sözün sahibini tartışır. Ziyaretçi, doğru hikâyeyi satın aldığını sanırken çoğu kez yeni bir borç alır.'],
  'ur-marak':['Toprak surların içi at pazarı, ateş takvimi ve açık meclislerle yaşar. Yangın kontrol ekipleri kentte asker kadar görünürdür.','Seçim ertelendikçe savaş tacı gündelik konuşmaların merkezine yerleşir; obalar şehre yalnız ticaret için değil oy hakkını hatırlatmak için gelir.'],
  'sessiz-oyuk':['Işık sızdırmayan salonlarda ses alçak tutulur; ticaret nötr tünelde, yüz yüze gelmeden yapılır.','Fener izleyicileri ve taş işçileri kapalı bir ritimle yaşar. Yabancının merakı, burada kötü niyet kadar tehlikeli kabul edilir.'],
  'can-kuyusu':['Katlar ayrı saat, hava ve ışık düzeniyle yaşar; yukarıdaki sabah aşağıda hâlâ gece olabilir.','Kobold bakım ekipleri, Gnom saatçileri ve su mühendisleri günlük hayatın gerçek otoritesidir. Bir grev, bütün katların birbirine ne kadar bağlı olduğunu hatırlatır.'],
  'vel-shaar':['İpek köprülerin gölgesinde mahalleler anne soy evlerinin ritmine göre yaşar; köprü desenleri hangi evin hangi kapıya güvenle gidebildiğini sessizce anlatır.','Dokumacılar, tapınak kâtipleri ve köprü bekçileri gündeliği taşır. Kül Örgüsü işaretlerinin kendiliğinden belirmesi, sıradan bir yürüyüşü bile siyasi bir yorum hâline getirir.'],
  'karanlik-liman':['Yeraltı denizinin tuzlu sisi rıhtımları kaplar; liman vergisi, çoğu zaman dinî kimlikten daha belirleyicidir.','Drow, Duergar, Kuo-Toa ve yüzey tüccarları aynı pazarda yaşar. Savaş zamanında bile malın geçmesi, tarafsızlığın sert kuralıdır.'],
  ayalti:['Yılda birkaç ay ışığı gecesinde şehir sokaklara taşar; yüzeyden gelen aileler ile sürgünler aynı gölgede buluşur.','Geri kalan zamanlarda mağara ağzı bekçi, rehber ve kaçış ağıyla yaşar. Ay ışığı burada romantik değil, siyasi bir takvimdir.'],
  'solmayan-koza':['Çürümeyen cesetler ve yaşlanmayan ipek, gündelik hayatı ürpertici bir sakinliğe sokar. Sakinler bunu koruma ve süreklilik sayar.','Mantar yetiştiricileri ile karantina bekçileri şehrin görünür emekçileridir; dış dünyanın korkusu, içerde kutsal düzen diye anlatılır.'],
  'kor-dum':['Vardiya değişimi meclis değişimi demektir; magma ışığı altında işçiler temsilci seçer.','Warforged komşularıyla aynı hukukta yaşamak gündelik bir gerçektir. Kar-Dur miras iddiası, yaşlıların hikâyesinden çok işçilerin özgürlük korkusudur.'],
  'kara-ors':['Zincir sarayların gölgesi alt platformlara düşer; sıcaklık ve yükseklik sınıf farkını her gün görünür kılar.','Soylular yukarıda, döküm işçileri aşağıda yaşar. Kaçak haber ve işçi geçişi, iki Duergar devletinin savaşsız çatışmasını besler.'],
  'bakir-baca':['Bacaların sesi ve sıcak hava vanaları şehrin hava durumudur. Bakım loncaları çocuklara bile hangi borunun hangi mahalleyi yaşattığını öğretir.','Ücret gecikmesi yalnız ekonomi değil, komşu şehrin havasını kesme tehdididir; bu yüzden Kobold teknisyenleri beklenmedik siyasi ağırlık taşır.'],
  'ilk-spor':['Sokak yerine ortak hafıza bölgeleri vardır; bir anı paylaşmak, bazen bir toplantıya katılmak demektir.','Spor toplayıcıları ve şifacılar gündelik ritmi kurar. Kara Hasat anılarının ağa girip girmemesi, her bireyin neyi hatırlamak istediği sorusudur.'],
  'balikci-ana':['Göl kıyısında ağlar, küçük tarlalar ve toplu ayinler aynı takvime bağlıdır. Bereket varlığı görünürse pazar sakinleşir.','Rahipler tarımı, balıkçılar inancı ve aileler ikisini birlikte taşır. Tanrıçanın suskunluğu, ekim kararlarını bile belirsizleştirir.'],
  'derin-nabiz':['Duvar yazıları ve deprem kuyuları şehirde yön tabelası gibidir. Grimlocklar titreşimle haber alır, yabancılar sessizliği yanlış okur.','Taş okuyucuları ve kuyu bekçileri günlük güvenliği sağlar. Yapay titreşimler, herkesin yürüdüğü zemine karşı yeni bir kuşku yaratmıştır.'],
  'mavi-tac':['Yaşayan mercan salonları büyütülür, inşa edilmez; yüzey elçileri Gelgit Aynası’nda bekler.','Bahçıvanlar, dalgıçlar ve mahkeme kâtipleri hayatı sürdürür. Nehir ağzı mahkemesi, deniz halkı için uzak diplomasi değil balıkçılık ve geçiş hakkıdır.'],
  'uclu-mizrak':['Üç çukurun akıntısı nöbet vardiyalarını belirler. Sütunlara bağlı evlerde deniz sesi hiç kesilmez.','Triton aileleri eğitim, devriye ve akıntı okumasını birlikte yürütür. Toplanan filolar, yüzeyden görünmeyen bir göçün gölgesini şehre taşır.'],
  'kirmizi-akinti':['Kan delil arşivleri ve av hukuku, pazar düzeni kadar gündeliktir. Kırmızı akıntılar şehrin takvimini belirler.','Savaşçılar, hakemler ve avcı aileleri aynı hukukta yaşar. Triton kanına dair söylenti, uzak diplomasi değil hangi ailenin güvenle avlanacağı sorusudur.'],
  'ilk-kiyi':['Manastıra dönen her yolcu tohum, hikâye ya da kural getirir; avlular sürekli değişen küçük bahçelerle doludur.','Tortle keşişleri ve yolcular ağır bir ritim kurar. Yasaklanan bilgi, sakin bir manastırı bütün yolların merak merkezine çevirmiştir.'],
  'bin-halat':['Yüzlerce tekne ve platformun halatları her sabah yeniden gerilir; bir kıyıya yanaşınca sokakların yönü değişir.','Halat ustaları, aşçılar ve pazar simsarı şehrin gerçek yöneticileridir. Ordan’ın ikmal teklifi, hareketli bir pazarın tarafsız kalıp kalamayacağını sorgulatır.']
}
const entry = computed(() => life[slug.value])
</script>
<template><section v-if="entry" class="capital-life"><p class="lore-kicker">Şehirde hayat</p><div class="lore-grid"><div class="lore-card"><h3>Gündelik ritim</h3><p>{{ entry[0] }}</p></div><div class="lore-card"><h3>İnsanlar ve mekân</h3><p>{{ entry[1] }}</p></div></div></section></template>
