<script setup>
import { computed } from 'vue'
import { useData } from 'vitepress'

const { page, lang } = useData()
const slug = computed(() => page.value.relativePath.replace(/^en\//, '').replace(/^devletler\//, '').replace(/\.md$/, ''))
const isEnglish = computed(() => lang.value.startsWith('en'))
const records = {
  'diken-taci': ['Diken Tacı · SS 83 siyasi ve ticari kayıt', 'Seçimli orman monarşisi; Elyra’nın Taht Ağacı’na dönüşmesi haleflik krizini büyütür. Kök Muhafızları, Açık Dal, Kızıl Av, Solgun Çember ve Boynuzsuz Ordu aynı geleceği istemez.', 'Lethar ile kültürel rekabet, Kar-Dur ile Demirkök ve maden gerilimi, Nehir Tahtı ile havza davası yaşar. Ordan kalıcı orman kalesi kurarsa savaş kaçınılmazdır; Yabanocak’ın izinsiz surlu devlet ilanı ikinci kırmızı çizgidir.', 'Metal, tuz ve büyük tahıl ithal eder; canlı kereste, lif, şifalı bitki ve nadir tohum ihraç eder. Diken–Meridyen Yolu Ordan kontrol noktaları ile Diken devriyeleri arasında bölünmüştür; Alt Dal ağı gizli kök postasını taşır.'],
  'ordan-imparatorlugu': ['Ordan İmparatorluğu · SS 83 siyasi ve ticari kayıt', 'Üçlü veraset savaşı başkenti bile bölmüştür: Varessa ordu ve Nareth işgalini, Odran bürokrasi-ticaret uzlaşmasını, Maelor ise dinî merkezîleşme ve Veyran üstünlüğünü savunur.', 'Diken Tacı ana askerî hedeftir; Lethar’la soğuk diplomasi, Kar-Dur’la temkinli teknik iş birliği, Nehir Tahtı’yla Namaris askerî limanı karşılığında baskılı pazarlık yürütür. Dokuz Fener’le antik yol haritaları için rekabet eder.', 'Kara ordusu Nareth tahılına ve Kırk Köprü kredisine bağımlıdır. Ordan Mührü ana kara ticaret parasıdır; Meridyen nehirleri, istasyon postası ve Seyvar–Nareth Boğaz Rotası imparatorluk denetimindedir.'],
  'lethar-yildiz-kralligi': ['Lethar · SS 83 siyasi ve ticari kayıt', 'On iki yaşındaki Kral Serel adına Aelor, Miravel ve Selent haneleri naiplik savaşı verir. Aelor soylu Yıldız Düzeni’ni, Miravel akademi ve Ayaz evliliğini, Selent ise kanal loncaları ile şehir reformunu savunur.', 'Ayaz Sarayı ile hanedan evliliği görüşür; Ordan adaylarıyla ayrı gizli temas kurar. Diken Tacı’yla rekabeti açık savaşa dönüşmemiştir; Bakır Prensliklerle kültürel yakınlık siyasi güven üretmez.', 'Tahıl, maden ve kereste ithal eder; büyü eğitimi, hassas zanaat ve sanat ihraç eder. Yıldız Bahçe Yolu Astereth’i Miravel, Bakır Meclis ve Yeşil Su limanlarına bağlar; Kuzey Buz Rotası kısa yazda kritikleşir.'],
  'kar-dur-tas-taci': ['Kar-Dur · SS 83 siyasi ve ticari kayıt', 'Kalıtsal taç ile ocak meclisleri birlikte yönetir. Veliaht Doran’ın dönüşü, yıllardır varis yetiştirilen küçük kardeşin destekçilerini ayaklanmaya yaklaştırır; Taç Ocakları, Derin Ustalar, Yeminliler, Açıcılar ve Warforged hareketi farklı çizgilerdedir.', 'Ordan’la Açıcılar üzerinden teknik temas kurar ama güvenmez. Dokuz Fener, Kor-Dum ve Kara Örs ile antik cüce mirası; Nehir Tahtı ile kaynak suları; Diken Tacı ile Demirkök ve yüzey ticareti konusunda çatışır.', 'Demir, silah ve taş mühendisliği temel güçtür. Taş Tacı Geçidi kışın kapanır; Döküm Hattı Kar-Dur, Kor-Dum ve Kara Örs arasında bölünmüş metal rotasıdır. Maden, katman ve ocak izinleri ayrı belge ister.'],
  'nehir-tahti': ['Nehir Tahtı · SS 83 siyasi ve ticari kayıt', 'Anaerkil seçimli monarşide Kraliçe Samara hastadır; aynı anda akıntılar yavaşlamaktadır. Nehir filosu ve su altı devriyeleri, suyun kaynağından deltaya kadar bütün havzayı siyasi beden sayan doktrini uygular.', 'Kar-Dur kaynaklarında, Diken Tacı kollarında ve Mercan Sarayları nehir ağızlarında ortak egemenlik iddia eder. Ordan, yardım karşılığında Namaris’te askerî liman ister; bu teklif hem ekonomik hem bağımsızlık krizidir.', 'İç ticaret ve nehir taşımacılığı devletin omurgasıdır. Namaris Pulu suya dayanıklı paradır; Üç Ağız Sistemi tahıl, tuz ve madeni denize bağlar. Akış krizi Halvek-Ordanor fiyatları ve Kırk Köprü borçları üzerinden kıtaya yayılır.'],
  'camova-konfederasyonu': ['Camova · SS 83 siyasi ve ticari kayıt', 'Şehir, kabile ve element ocakları meclisi beş yılda bir yer değiştirir; SS 83 toplantısı Yankıtaş’tadır. Ordan yanlıları yol-güvenlik isterken bağımsızlıkçılar maden sayımının ilhaka dönüşeceğinden korkar.', 'Ordan ile yol antlaşması görüşmeleri, Hal-Sur ile Soluk Çanak Çevre Yolu ve Nareth piyasaları siyasi ağırlık taşır. Sabit başkent olmaması zayıflık değil, tek bölgenin üstünleşmesini engelleyen konfederasyon ilkesidir.', 'Obsidyen, kristal hafıza, volkanik tarım ve haritacılık üretir. Kristal kayıtların kamusallığı şehir hukukunun konusudur; hafıza kristalleri hem ticari mal hem diplomatik kanıttır.'],
  'sis-adalari-cumhuriyeti': ['Sis Adaları · SS 83 siyasi ve ticari kayıt', 'Ticaret konseyleri ile kimliği gizli Dokuzuncu Masa yönetir. Tarafsızlık görünümü altında hiçbir kıta gücünün kesin zaferini istemez; aynı anda rakip aday ve devletlerle çalışır.', 'Ordan, Lethar, insan hanedanları ve Labirent Limanlarıyla paralel anlaşmalar kurar. Velis’te birden fazla yasal kimlik mümkündür; her kimlik kendi borç kaydını taşır.', 'Sigorta, kredi, bilgi, kimlik ve tarafsız müzakere ana ekonomidir. Sis Senedi yük veya kimlik teminatlı ödeme belgesidir; Sis Zinciri rotası yerel kılavuz olmadan tehlikelidir.'],
  'tuz-ocaklari-cumhuriyeti': ['Tuz Ocakları · SS 83 siyasi ve ticari kayıt', 'Maden hissedarı ailelerin oligark meclisi Hal-Sur’dan yönetir. Goblin ve Kobold çoğunluk yurttaşlık ister; en eski mahzende yeniden bilinç gösteren ölü hissedar söylentisi meclis dengelerini bozabilir.', 'Resmen tarafsızdır; Ordan, Kar-Dur ve Sis Adaları antik yol haritalarına farklı aracılarla para öder. Bu gizli satış, tarafsızlığın hem geliri hem en büyük riski olur.', 'Tuz, simya minerali, fosil ve koruma ekonomisinin merkezidir. Hal-Sur Payı depo makbuzu ve tuz hissesi olarak yüksek ticarette kullanılır; Soluk Çanak Çevre Yolu Durgunluk yüzünden uzamıştır.'],
  'ayaz-sarayi': ['Ayaz Sarayı · SS 83 siyasi ve ticari kayıt', 'Ayaz Kraliçesi Ilyvara Nivarra’dan hükmeder ve Prens Odran’ı destekler. Buz arşivleri antlaşma, delil ve cesetleri yüzyıllarca saklar; erime, geçmiş savaşların hâlâ yaşayan tanıklarını açığa çıkarır.', 'Lethar’la hanedan evliliği Ayaz’ın ana diplomasisidir; Odran desteği Ordan verasetini kuzey ticaretine bağlar. Kuzey yollarının denetimi siyasetin temel hedefidir.', 'Kuzey Buz Rotası kısa yazda Lethar, Nivarra ve cüce ocaklarını bağlar. Buz arşivleri ve soğuk depolama, ticaret kadar hukukî üstünlük de üretir.'],
  'altin-gunes-kralligi': ['Altıngüneş · SS 83 siyasi ve ticari kayıt', 'Solkar’daki ikiz hükümdarların ikisi de savaş tacını ister; hasat tacı boş kaldığı için yönetim ve su depoları ihmal edilir. Bu veraset biçimi doğrudan bir gıda güvenliği krizine dönüşmektedir.', 'General Varessa’ya asker ve ateş silahı satmaya yakındır; bu tercih Ordan iç savaşını Odraka ve mevsim devletlerine taşır.', 'Şarap, baharat ve paralı asker ticareti güçlüdür; su depoları zayıftır. Güney Baharat Rotası üzerinden Labirent Limanları ve Nareth limanlarıyla bağlıdır.'],
  'bakir-prenslikler': ['Bakır Prenslikler · SS 83 siyasi ve ticari kayıt', 'Yedi prenslik ortak ordu kuramaz; Bakır Meclis tarafsız diplomasi merkezidir. Düşen Taç prensliğinin boş oyunun kimce kullanılacağı ortak hukuku krize sokmuştur.', 'Lethar’la kültürel yakınlık taşır fakat siyasi güven sınırlıdır. Dhampir cenaze ailelerinin bilgi ağı, prensliklerin görünmez diplomatik kapasitesidir.', 'Yıldız Bahçe Yolu ve cenaze/hatıra hizmetleri ticari bağlantıyı güçlendirir; geçici yaprak köşkleri sabit hanedan egemenliğini reddeden şehir hukukunun parçasıdır.'],
  'yesil-su-birligi': ['Yeşil Su Birliği · SS 83 siyasi ve ticari kayıt', 'Beş şehir devletinde tüccar aileleri ile mevsim rahipleri iktidar için mücadele eder. Filizliman’ın ilkbahar borç affı geleneği bankacılarla rahipleri açık çatışmaya taşır.', 'Dış politika fiilen Filizliman’dan yürür. Lethar ve kıyı limanlarıyla Yıldız Bahçe Yolu üzerinden bağlanır; yerel borç hukuku dış krediyi de etkiler.', 'Liman, tohum, ilaç ve Halfling bankaları ekonomik gücüdür. Genel borç affı gerçekleşirse yalnız şehirde değil, kredi ağlarında da zincirleme etki doğar.'],
  'saarin-iki-ejderha-taci': ['Saar’ın İki Ejderha Tacı · SS 83 siyasi ve ticari kayıt', 'Kızıl Saar ejderha soylu hanedanlarıyla İlk Ejderhaların yönetim mirasını savunur; Prizma merkezli Mücevher Yemini ise soy üstünlüğünü reddedip zihin disiplini ve şehir konseylerini öne çıkarır.', 'Kızıl Saar Altıngüneş ve Ordan ordusuyla askerî ticaret yapar. Mücevher Yemini Dokuz Fener ve bazı Svirfneblin kentleriyle ittifak kurar; iki tarafın miras savaşı Odraka’yı bölme potansiyeli taşır.', 'Saar-Kor’un kalderası, Prizma’nın kristal hafızası ve Odraka yolları ekonomik olduğu kadar ideolojik kaynaklardır. Demir ve askerî üretim Serath-Kar-Dur hattıyla rekabet eder.'],
  'dokuz-fener-birligi': ['Dokuz Fener · SS 83 siyasi ve ticari kayıt', 'Dokuz kentli konfederasyonda Son Parıltı koltuğu boştur; yeni oy pusulası meclisi böler. Kırık Fener askerî yetki isterken kentler ortak savunmanın sınırında uzlaşamaz.', 'Kar-Dur antik miras iddiası taşır; Ordan harita rekabeti yürütür; Nehir Tahtı su mühendisliğiyle bağ kurar. Sessiz Oyuk birlik dışı kalarak bazı antik kayıtları saklar.', 'Kristal, optik, mekanik ve Yankı kaydı yeraltı ekonomisinin gücüdür. Oyuk Halkası güvenli konfederasyon yolu, Antik Damar Yolları ise hızlı fakat paylaşılmayan tehlikeli ağdır.']
}
const record = computed(() => records[slug.value])
</script>

<template>
  <section v-if="record && !isEnglish" class="state-relations">
    <p class="lore-kicker">{{ record[0] }}</p>
    <div class="lore-grid"><div class="lore-card"><h3>İç siyaset</h3><p>{{ record[1] }}</p></div><div class="lore-card"><h3>Dış ilişkiler</h3><p>{{ record[2] }}</p></div><div class="lore-card"><h3>Ekonomi ve ulaşım</h3><p>{{ record[3] }}</p></div></div>
  </section>
</template>
